[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"

[[headers]]
  for = "*.css"  
  [headers.values]
    Content-Type = "text/css; charset=UTF-8"

[[redirects]]
  from = "/api/simple-auth"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/simple-login"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/payment-webhook"
  to = "/.netlify/functions/payment-webhook"
  status = 200

[[redirects]]
  from = "/api/analytics"
  to = "/.netlify/functions/analytics"
  status = 200

[[redirects]]
  from = "/api/ai-interpreter"
  to = "/.netlify/functions/ai-interpreter"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  functions = "netlify/functions"
  publish = "dist"