[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/simple-auth"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/simple-login"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/payment-webhook"
  to = "/.netlify/functions/payment-webhook"
  status = 200

[[redirects]]
  from = "/api/analytics"
  to = "/.netlify/functions/analytics"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  functions = "netlify/functions"
  publish = "dist"